# Munta's Basic tmuxtopf
# Based on craftzdog's

# action key
unbind C-b
set-option -g prefix C-t
set-option -g repeat-time 0
# set -as terminal-features ",gnome*:RGB"

#### Key bindings
set-window-option -g mode-keys vi
unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

# Tmux Appearance -------------------- {{{
set -g default-terminal "screen-256color"
set -g status-left " #S "
set -g status-left-length 13
set -g status-left-style fg=#eee8d5,bold,bg=#6700b5

set -g window-status-current-style fg=#eee8d5,bold,bg=#b58900
set -g window-status-current-format "#{?window_last_flag,`, }#{?window_zoomed_flag,[,}#I:#W#{?window_zoomed_flag,],}#{?window_last_flag,`, }"
set -g window-status-format "#{?window_last_flag,`, }#{?window_zoomed_flag,[,}#I:#W#{?window_zoomed_flag,],}#{?window_last_flag,`, }"

set -g status-style fg=colour241,bg=colour233
# #h hostshort , #S session , #W window , #T pane name
wg_prfx=" #[fg=colour231,bg=default]#{?client_prefix,<Prefix>,}"  # prefix indicator widget
wg_pane=" #[fg=colour202,bg=default]#{=26:pane_title}"
wg_date=" #[fg=colour231,bold,italics,bg=default]%d-%b-%Y#[none]"
wg_time=" #[fg=colour220,bold,bg=default]%H:%M"
set -g status-right "${wg_prfx}${wg_pane}${wg_date}${wg_time}"
# }}}


#bind t send-key C-t
# Reload settings
bind r source-file ~/.tmux.conf \; display "Reloaded!"
# Open current directory
bind o run-shell "open #{pane_current_path}"
bind -r e kill-pane -a

# Moving window
bind-key -n C-S-Left swap-window -t -1 \; previous-window
bind-key -n C-S-Right swap-window -t +1 \; next-window

# Resizing pane
bind -r k resize-pane -U 5
bind -r j resize-pane -D 5
bind -r h resize-pane -L 5
bind -r l resize-pane -R 5

#### basic settings

set-option -g status-justify left
set-option -g status-position bottom
#set-option utf8-default on
set -g mouse on
set-window-option -g mode-keys vi
#set-window-option -g utf8 on
set -sg escape-time 10
# default shell
set-option -g default-shell /bin/zsh
# transparent bg
set-option -g status-style bg=default


#### plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'

run '~/.tmux/plugins/tpm/tpm'
