# ~/.config/starship.toml
# a theme based off robbyrussell

# Format for prompt line: <username> @ <hostname> in <directory>
format = "$all "

[username]
# Show the username if it's not the default user
show_always = false

[hostname]
# Show hostname
disabled = true

[directory]
# Style for the directory path
style = "cyan"
truncation_length = 3

[git_branch]
# Git branch in a style similar to robbyrussell
symbol = ""
style = "bold purple"

[git_status]
# Git status indicators
conflicted = "≠"
ahead = "↑·"
behind = "↓·"
diverged = "↕·"
untracked = "?"
modified = "✚"
staged = "✖"
renamed = "»"
deleted = "✖"

[character]
# The prompt character like robbyrussell
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

# disabled stuff
[nodejs]
disabled = true

[cmd_duration]
disabled = true
